version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy/service

permissions:
  - object: /home/ubuntu/deploy/service
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 1000
      runas: ubuntu
