export const PROJECT_LIST_KEY = ['project', 'list']
export const PROJECT_DETAIL_KEY = ['project', 'detail']
export const LIKE_STATE_KET = ['']
export const IS_LEADER_KEY = ['is-leader']
export const USER_KEY = ['user']
