export const PROJECT_LIST_KEY = ['project', 'list']
export const PROJECT_DETAIL_KEY = ['project', 'detail']
export const LIKE_STATE_KEY = ['like-info']
export const IS_LEADER_KEY = ['is-leader']
export const USER_KEY = ['user']
export const MANAGE_MY_TEAM_KEY = ['project', 'manage']
export const MANAGE_MY_TEAM_DETAIL_KEY = ['project', 'manage', 'detail']
export const NOT_APPROVED_MEMBER_KEY = ['not-approved-member']
